name: FluidStories
version: 0.1
author: Rachael Little
main: us.nyrene.fluidstories.main
api-version: 1.14


commands:
    spawnnpc:
      description: Creates an NPC with the given name at your look location.
      usage: /spawnnpc <name>

    setnpcdesc:
      description: Sets the selected NPC's description
      usage: /setnpcdesc <name> <description>

    looknpc:
      description: Prints the selected NPC's description if it has one
      usage: /looknpc <name>

    removenpc:
      description: Removes the named NPC.
      usage: /removenpc <name>

    talknpc:
      description: Starts a conversation with the named NPC.
      usage: /talknpc <name>

    say:
      description: Once a conversation has been started, selects dialogue options.
      usage: /say <number>

    fs:
      description: Command set for creating and editing dialogues
      usage: /fs <subcommand> <args>
